In [1]:
import numpy as np

In [2]:
list = [0,1,2,3,4,5]

In [3]:
arr = np.array(list)

In [4]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(0,10) # fill the array with the numbers in the range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2) # fill the array with the numbers in the range following the step size

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.random.seed(101) # seed is like a collection of selected random numbers
arr = np.random.randint(0,100,10) # fill the array with a number of (10) random values in the range

In [10]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [11]:
arr2 = np.random.randint(0,100,10)

In [12]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [13]:
arr.max() # Highest element in the array

95

In [14]:
arr.argmax() # index number of the highest element in the array

0

In [15]:
arr.min() # lowest element in the array

9

In [16]:
arr.argmin() # index number of the lowest element in the array

7

In [19]:
arr.shape # shape of the array

(10,)

In [21]:
arr.reshape(5,2) # remember : the multiplication of the row and column must match with the original
                            # shape value. Otherwise it will give an error

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [22]:
mat = np.arange(0,100).reshape(10,10)

In [23]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
row = 1
col = 0
mat[row,col]

10

In [25]:
mat[:,col] # elements of all rows and selected column (0)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
mat[row,:] # element of selected row (1) and all columns 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
mat[0:5, 0:5] # elements of row 0 to 5 and column 0 to 5. This is called "Slicing"

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])